import { useCallback, useEffect, useState } from 'react';
import styles from './AdminEmploymentInterestsPage.module.css';
import { Seo } from '@/lib/seo/Seo';
import { Button } from '@/components/ui/Button';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/States';
import { apiRequest, ApiError } from '@/lib/api/client';
import { antiforgeryToken } from '@/lib/api/admin';

type Status='Pending'|'Confirmed'|'Declined'|'Completed'|'Cancelled';
interface Booking { id:number;firstName:string;lastName:string;email:string;phone:string;preferredDate:string;preferredTime:string;alternateDate:string|null;alternateTime:string|null;address:string;city:string;state:string;postalCode:string;projectDescription:string;notes:string|null;status:Status;adminNotes:string|null;createdAtUtc:string;updatedAtUtc:string|null;confirmedAtUtc:string|null;completedAtUtc:string|null;cancelledAtUtc:string|null;rowVersion:string; }
const statuses: readonly (Status|'All')[]=['All','Pending','Confirmed','Completed','Declined','Cancelled'];

export default function AdminBookingsPage(){
  const [items,setItems]=useState<Booking[]>([]);const [filter,setFilter]=useState<Status|'All'>('All');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [saving,setSaving]=useState<number|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await apiRequest<Booking[]>(`/api/admin/bookings${filter==='All'?'':`?status=${filter}`}`));}catch(reason){setError(reason instanceof ApiError?reason.message:'Bookings could not be loaded.');}finally{setLoading(false);}},[filter]);
  useEffect(()=>{let active=true;apiRequest<Booking[]>(`/api/admin/bookings${filter==='All'?'':`?status=${filter}`}`).then(data=>{if(active){setItems(data);setLoading(false);}}).catch((reason:unknown)=>{if(active){setError(reason instanceof ApiError?reason.message:'Bookings could not be loaded.');setLoading(false);}});return()=>{active=false;};},[filter]);
  const update=(id:number,patch:Partial<Booking>)=>setItems(current=>current.map(item=>item.id===id?{...item,...patch}:item));
  async function save(item:Booking){setSaving(item.id);setError(null);try{const saved=await apiRequest<Booking>(`/api/admin/bookings/${item.id}`,{method:'PUT',antiforgeryToken:await antiforgeryToken(),body:{status:item.status,adminNotes:item.adminNotes,rowVersion:item.rowVersion}});update(item.id,saved);}catch(reason){setError(reason instanceof ApiError?reason.message:'That booking could not be saved.');}finally{setSaving(null);}}
  return <><Seo title="Bookings · Admin" description="Private booking-request management." path="/admin/bookings" noIndex/><header className={styles.header}><p>Customers</p><h1>Booking requests</h1><span>Requested times are pending until you confirm them.</span></header>
    <div className={styles.actions} role="group" aria-label="Filter bookings">{statuses.map(status=><Button key={status} type="button" size="sm" variant={filter===status?'primary':'secondary'} onClick={()=>{setLoading(true);setError(null);setFilter(status);}}>{status}</Button>)}</div>
    {error?<p role="alert">{error}</p>:null}{loading?<LoadingState label="Loading booking requests" variant="inline"/>:error&&items.length===0?<ErrorState title="We could not load bookings" onRetry={load}/>:items.length===0?<EmptyState title="No booking requests found" description="New requests from the Bookings page will appear here."/>:<div className={styles.list}>{items.map(item=><article className={styles.card} key={item.id}><div className={styles.top}><div><h2>{item.firstName} {item.lastName}</h2><p>Submitted {new Date(item.createdAtUtc).toLocaleString()}</p></div><select aria-label={`Status for ${item.firstName} ${item.lastName}`} value={item.status} onChange={event=>update(item.id,{status:event.target.value as Status})}>{statuses.filter(x=>x!=='All').map(x=><option key={x}>{x}</option>)}</select></div><dl><div><dt>Contact</dt><dd><a href={`mailto:${item.email}`}>{item.email}</a> · <a href={`tel:${item.phone}`}>{item.phone}</a></dd></div><div><dt>Preferred</dt><dd>{item.preferredDate} at {item.preferredTime}</dd></div>{item.alternateDate?<div><dt>Alternate</dt><dd>{item.alternateDate} at {item.alternateTime}</dd></div>:null}<div><dt>Location</dt><dd>{item.address}, {item.city}, {item.state} {item.postalCode}</dd></div><div><dt>Exterior project</dt><dd>{item.projectDescription}</dd></div>{item.notes?<div><dt>Customer notes</dt><dd>{item.notes}</dd></div>:null}</dl><label>Admin notes<textarea rows={4} maxLength={4000} value={item.adminNotes??''} onChange={event=>update(item.id,{adminNotes:event.target.value})}/></label><div className={styles.actions}><Button type="button" size="sm" loading={saving===item.id} onClick={()=>void save(item)}>Save booking</Button></div></article>)}</div>}</>;
}
