/**
 * Admin API contract types.
 *
 * These mirror `KellumsSecondChance.Server/Dtos/AdminDtos.cs`. The server is the
 * source of truth for shape and nullability — anything optional here is
 * optional there, and vice versa.
 *
 * Nothing in this file is used by the public site; it is only reachable from the
 * lazily-loaded admin bundle.
 */

import type {
  BudgetRange,
  OfficeHours,
  EstimateRequestStatus,
  ImageAsset,
  PreferredContactMethod,
  ProjectImageKind,
  ProjectTimeline,
  PropertyType,
  ServiceAreaKind,
  SocialLink,
} from './types';

/* ---------------------------------------------------------------- projects */

export interface AdminProjectImage {
  readonly id: number;
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly alt: string;
  readonly kind: ProjectImageKind;
  readonly caption: string | null;
  readonly displayOrder: number;
  /** Ties a Before to its matching After. Generated by the server. */
  readonly pairKey: string | null;
  /** False for artwork that shipped with the app rather than being uploaded. */
  readonly isUploaded: boolean;
  readonly fileSizeBytes: number | null;
}

export interface AdminProjectListItem {
  readonly id: number;
  readonly slug: string;
  readonly title: string;
  readonly categoryName: string;
  readonly location: string | null;
  readonly isFeatured: boolean;
  readonly isActive: boolean;
  readonly isSampleContent: boolean;
  readonly displayOrder: number;
  readonly completedOn: string | null;
  readonly imageCount: number;
  readonly hasCoverImage: boolean;
  readonly hasBeforeAfter: boolean;
  readonly updatedAtUtc: string | null;
}

export interface AdminProject {
  readonly id: number;
  readonly slug: string;
  readonly title: string;
  readonly categoryName: string;
  readonly categorySlug: string;
  readonly location: string | null;
  readonly summary: string;
  readonly challenge: string;
  readonly vision: string;
  readonly transformation: string;
  readonly outcome: string | null;
  readonly completedOn: string | null;
  readonly durationLabel: string | null;
  readonly propertyType: string | null;
  readonly highlights: readonly string[];
  readonly serviceIds: readonly number[];
  readonly isFeatured: boolean;
  readonly isActive: boolean;
  readonly isSampleContent: boolean;
  readonly displayOrder: number;
  readonly metaTitle: string | null;
  readonly metaDescription: string | null;
  readonly images: readonly AdminProjectImage[];
  readonly createdAtUtc: string;
  readonly updatedAtUtc: string | null;
  readonly rowVersion: string | null;
}

/** What the project form sends. Mirrors ProjectWriteDto. */
export interface ProjectWrite {
  readonly title: string;
  /** Omit on create to derive from the title; omit on update to keep the URL. */
  readonly slug?: string | null;
  readonly categoryName: string;
  readonly categorySlug: string;
  readonly location: string | null;
  readonly summary: string;
  readonly challenge: string;
  readonly vision: string;
  readonly transformation: string;
  readonly outcome: string | null;
  readonly completedOn: string | null;
  readonly durationLabel: string | null;
  readonly propertyType: string | null;
  readonly highlights: readonly string[];
  readonly serviceIds: readonly number[];
  readonly isFeatured: boolean;
  readonly isActive: boolean;
  readonly displayOrder: number;
  readonly metaTitle: string | null;
  readonly metaDescription: string | null;
  readonly rowVersion?: string | null;
}

export interface ProjectImageUpdate {
  readonly altText: string;
  readonly caption: string | null;
  readonly kind: ProjectImageKind;
  readonly displayOrder: number;
  readonly pairKey: string | null;
}

/** A standalone image: a service photograph, or the social sharing card. */
export interface UploadedImage {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly alt: string;
  readonly sizeBytes: number;
}

export interface BeforeAfterPairWrite {
  readonly beforeImageId: number | null;
  readonly afterImageId: number | null;
  /** Null creates a new pair. */
  readonly pairKey: string | null;
}

/* ---------------------------------------------------------------- services */

export interface AdminService {
  readonly id: number;
  readonly slug: string;
  readonly name: string;
  readonly tagline: string;
  readonly summary: string;
  readonly icon: string;
  readonly headline: string;
  readonly introduction: string;
  readonly includes: readonly string[];
  readonly bestFor: readonly string[];
  readonly considerations: readonly string[];
  readonly image: ImageAsset | null;
  readonly isFeatured: boolean;
  readonly isActive: boolean;
  readonly displayOrder: number;
  readonly metaTitle: string | null;
  readonly metaDescription: string | null;
  /** Projects pointing at this service. A service in use cannot be deleted. */
  readonly linkedProjectCount: number;
  readonly updatedAtUtc: string | null;
  readonly rowVersion: string | null;
}

export interface ServiceWrite {
  readonly name: string;
  readonly slug?: string | null;
  readonly tagline: string;
  readonly summary: string;
  readonly icon: string;
  readonly headline: string;
  readonly introduction: string;
  readonly includes: readonly string[];
  readonly bestFor: readonly string[];
  readonly considerations: readonly string[];
  readonly isFeatured: boolean;
  readonly isActive: boolean;
  readonly displayOrder: number;
  readonly metaTitle: string | null;
  readonly metaDescription: string | null;
  readonly rowVersion?: string | null;
}

/* ------------------------------------------------------------ testimonials */

export type TestimonialSource = 'Direct' | 'Google' | 'Facebook' | 'Other';

export interface AdminTestimonial {
  readonly id: number;
  readonly firstName: string;
  readonly lastInitial: string | null;
  readonly location: string | null;
  readonly rating: number;
  readonly quote: string;
  readonly projectCategory: string | null;
  readonly reviewedOn: string | null;
  readonly isFeatured: boolean;
  readonly isActive: boolean;
  /** Seeded demonstration copy. Labelled on the public site; never settable here. */
  readonly isSampleContent: boolean;
  readonly displayOrder: number;
  readonly source: TestimonialSource;
  readonly updatedAtUtc: string | null;
}

export interface TestimonialWrite {
  readonly firstName: string;
  readonly lastInitial: string | null;
  readonly location: string | null;
  readonly rating: number;
  readonly quote: string;
  readonly projectCategory: string | null;
  readonly reviewedOn: string | null;
  readonly isFeatured: boolean;
  readonly isActive: boolean;
  readonly displayOrder: number;
  readonly source: TestimonialSource;
}

/* --------------------------------------------------------------------- faq */

export interface AdminFaq {
  readonly id: number;
  readonly question: string;
  readonly answer: string;
  readonly category: string;
  readonly categorySlug: string;
  /** While true the question is withheld from the site and from FAQ markup. */
  readonly needsReview: boolean;
  readonly reviewNote: string | null;
  readonly isActive: boolean;
  readonly displayOrder: number;
  readonly updatedAtUtc: string | null;
  readonly rowVersion: string | null;
}

export interface FaqWrite {
  readonly question: string;
  readonly answer: string;
  readonly category: string;
  readonly categorySlug: string;
  readonly needsReview: boolean;
  readonly reviewNote: string | null;
  readonly isActive: boolean;
  readonly displayOrder: number;
  readonly rowVersion?: string | null;
}

/* ----------------------------------------------------------- service areas */

export interface AdminServiceArea {
  readonly id: number;
  readonly name: string;
  readonly kind: ServiceAreaKind;
  readonly stateOrRegion: string | null;
  readonly postalCodes: readonly string[];
  readonly isPrimary: boolean;
  readonly note: string | null;
  readonly isActive: boolean;
  /** A stand-in entry the business has not confirmed. */
  readonly isSampleContent: boolean;
  readonly displayOrder: number;
  readonly updatedAtUtc: string | null;
}

export interface ServiceAreaWrite {
  readonly name: string;
  readonly kind: ServiceAreaKind;
  readonly stateOrRegion: string | null;
  readonly postalCodes: readonly string[];
  readonly isPrimary: boolean;
  readonly note: string | null;
  readonly isActive: boolean;
  readonly displayOrder: number;
}

/* ------------------------------------------------------------ site settings */

export interface AdminSiteSettings {
  readonly businessName: string | null;
  readonly tagline: string | null;
  readonly phoneDisplay: string | null;
  readonly phoneE164: string | null;
  readonly email: string | null;
  readonly addressLine1: string | null;
  readonly addressLine2: string | null;
  readonly addressLocality: string | null;
  readonly addressRegion: string | null;
  readonly addressPostalCode: string | null;
  readonly publishAddress: boolean;
  readonly serviceAreaSummary: string | null;
  readonly licensing: string | null;
  readonly insurance: string | null;
  readonly foundedYear: number | null;
  readonly socialLinks: readonly SocialLink[];
  readonly officeHours: readonly OfficeHours[];
  readonly siteUrl: string | null;
  readonly ogImagePath: string | null;
}

/** Same shape; a blank string clears the stored value. */
export type SiteSettingsWrite = Omit<AdminSiteSettings, 'socialLinks' | 'officeHours'> & {
  readonly socialLinks: readonly SocialLink[];
  readonly officeHours: readonly OfficeHours[];
};

/* -------------------------------------------------------- estimate requests */

export interface EstimateRequestNote {
  readonly id: number;
  readonly note: string;
  readonly createdAtUtc: string;
  readonly createdByDisplayName: string | null;
}

export interface EstimateRequestStatusHistoryEntry {
  readonly id: number;
  readonly previousStatus: EstimateRequestStatus;
  readonly newStatus: EstimateRequestStatus;
  readonly changedAtUtc: string;
  readonly changedByDisplayName: string | null;
}

export interface AdminEstimateRequestDetail {
  readonly request: {
    readonly id: number;
    readonly reference: string;
    readonly firstName: string;
    readonly lastName: string;
    readonly email: string;
    readonly phone: string | null;
    readonly projectTypes: readonly string[];
    readonly propertyType: PropertyType;
    readonly addressLine: string | null;
    readonly city: string | null;
    readonly postalCode: string;
    readonly timeline: ProjectTimeline;
    readonly budgetRange: BudgetRange;
    readonly description: string;
    readonly preferredContactMethod: PreferredContactMethod;
    readonly referralSource: string | null;
    readonly status: EstimateRequestStatus;
    /**
     * A single free-text note from before the activity log existed. Read-only:
     * new notes go into the journal below.
     */
    readonly internalNotes: string | null;
    readonly createdAtUtc: string;
    readonly updatedAtUtc: string | null;
  };
  readonly notes: readonly EstimateRequestNote[];
  readonly history: readonly EstimateRequestStatusHistoryEntry[];
  readonly rowVersion: string | null;
}

export type EstimateRequestSort = 'NewestFirst' | 'OldestFirst' | 'Customer' | 'Status';

/* ------------------------------------------------------------- dashboard */

export interface DashboardMetrics {
  readonly newLeads: number;
  readonly awaitingFollowUp: number;
  readonly estimatesScheduled: number;
  readonly estimatesSent: number;
  readonly won: number;
  readonly lost: number;
  readonly archived: number;
  readonly totalLeads: number;
  readonly leadsLast30Days: number;
  readonly publishedProjects: number;
  readonly draftProjects: number;
  readonly publishedServices: number;
  readonly inactiveServices: number;
  readonly publishedTestimonials: number;
  readonly unpublishedTestimonials: number;
  readonly publishedFaqs: number;
  readonly faqsAwaitingReview: number;
  readonly activeServiceAreas: number;
}

export type AttentionSeverity = 'urgent' | 'action' | 'info';

export interface AttentionItem {
  readonly kind: string;
  readonly title: string;
  readonly detail: string;
  readonly actionPath: string;
  readonly severity: AttentionSeverity;
}
